
prototype:
  build: ./Prototype
  ports:
    - "8000:8000"

web:
  build: ./Backend
  ports:
    - "5000:5000"
  links:
    - db
    - prototype

db:
  image: mongo:3.0.2

front:
  build: ./Frontend
  ports:
    - "3000:80"
  links:
    - web
